spring.application.name=review-service

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/reviewdb
spring.datasource.username=root
spring.datasource.password=hitesh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true